# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fahad-ubuntu/Downloads/px4-jsbsim-bridgesept

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fahad-ubuntu/Downloads/px4-jsbsim-bridgesept

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fahad-ubuntu/Downloads/px4-jsbsim-bridgesept/CMakeFiles /home/fahad-ubuntu/Downloads/px4-jsbsim-bridgesept/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fahad-ubuntu/Downloads/px4-jsbsim-bridgesept/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jsbsim_bridge

# Build rule for target.
jsbsim_bridge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsbsim_bridge
.PHONY : jsbsim_bridge

# fast build rule for target.
jsbsim_bridge/fast:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/build
.PHONY : jsbsim_bridge/fast

src/actuator_plugin.o: src/actuator_plugin.cpp.o

.PHONY : src/actuator_plugin.o

# target to build an object file
src/actuator_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/actuator_plugin.cpp.o
.PHONY : src/actuator_plugin.cpp.o

src/actuator_plugin.i: src/actuator_plugin.cpp.i

.PHONY : src/actuator_plugin.i

# target to preprocess a source file
src/actuator_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/actuator_plugin.cpp.i
.PHONY : src/actuator_plugin.cpp.i

src/actuator_plugin.s: src/actuator_plugin.cpp.s

.PHONY : src/actuator_plugin.s

# target to generate assembly for a file
src/actuator_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/actuator_plugin.cpp.s
.PHONY : src/actuator_plugin.cpp.s

src/configuration_parser.o: src/configuration_parser.cpp.o

.PHONY : src/configuration_parser.o

# target to build an object file
src/configuration_parser.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/configuration_parser.cpp.o
.PHONY : src/configuration_parser.cpp.o

src/configuration_parser.i: src/configuration_parser.cpp.i

.PHONY : src/configuration_parser.i

# target to preprocess a source file
src/configuration_parser.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/configuration_parser.cpp.i
.PHONY : src/configuration_parser.cpp.i

src/configuration_parser.s: src/configuration_parser.cpp.s

.PHONY : src/configuration_parser.s

# target to generate assembly for a file
src/configuration_parser.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/configuration_parser.cpp.s
.PHONY : src/configuration_parser.cpp.s

src/geo_mag_declination.o: src/geo_mag_declination.cpp.o

.PHONY : src/geo_mag_declination.o

# target to build an object file
src/geo_mag_declination.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/geo_mag_declination.cpp.o
.PHONY : src/geo_mag_declination.cpp.o

src/geo_mag_declination.i: src/geo_mag_declination.cpp.i

.PHONY : src/geo_mag_declination.i

# target to preprocess a source file
src/geo_mag_declination.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/geo_mag_declination.cpp.i
.PHONY : src/geo_mag_declination.cpp.i

src/geo_mag_declination.s: src/geo_mag_declination.cpp.s

.PHONY : src/geo_mag_declination.s

# target to generate assembly for a file
src/geo_mag_declination.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/geo_mag_declination.cpp.s
.PHONY : src/geo_mag_declination.cpp.s

src/jsbsim_bridge.o: src/jsbsim_bridge.cpp.o

.PHONY : src/jsbsim_bridge.o

# target to build an object file
src/jsbsim_bridge.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/jsbsim_bridge.cpp.o
.PHONY : src/jsbsim_bridge.cpp.o

src/jsbsim_bridge.i: src/jsbsim_bridge.cpp.i

.PHONY : src/jsbsim_bridge.i

# target to preprocess a source file
src/jsbsim_bridge.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/jsbsim_bridge.cpp.i
.PHONY : src/jsbsim_bridge.cpp.i

src/jsbsim_bridge.s: src/jsbsim_bridge.cpp.s

.PHONY : src/jsbsim_bridge.s

# target to generate assembly for a file
src/jsbsim_bridge.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/jsbsim_bridge.cpp.s
.PHONY : src/jsbsim_bridge.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mavlink_interface.o: src/mavlink_interface.cpp.o

.PHONY : src/mavlink_interface.o

# target to build an object file
src/mavlink_interface.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/mavlink_interface.cpp.o
.PHONY : src/mavlink_interface.cpp.o

src/mavlink_interface.i: src/mavlink_interface.cpp.i

.PHONY : src/mavlink_interface.i

# target to preprocess a source file
src/mavlink_interface.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/mavlink_interface.cpp.i
.PHONY : src/mavlink_interface.cpp.i

src/mavlink_interface.s: src/mavlink_interface.cpp.s

.PHONY : src/mavlink_interface.s

# target to generate assembly for a file
src/mavlink_interface.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/mavlink_interface.cpp.s
.PHONY : src/mavlink_interface.cpp.s

src/sensor_airspeed_plugin.o: src/sensor_airspeed_plugin.cpp.o

.PHONY : src/sensor_airspeed_plugin.o

# target to build an object file
src/sensor_airspeed_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_airspeed_plugin.cpp.o
.PHONY : src/sensor_airspeed_plugin.cpp.o

src/sensor_airspeed_plugin.i: src/sensor_airspeed_plugin.cpp.i

.PHONY : src/sensor_airspeed_plugin.i

# target to preprocess a source file
src/sensor_airspeed_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_airspeed_plugin.cpp.i
.PHONY : src/sensor_airspeed_plugin.cpp.i

src/sensor_airspeed_plugin.s: src/sensor_airspeed_plugin.cpp.s

.PHONY : src/sensor_airspeed_plugin.s

# target to generate assembly for a file
src/sensor_airspeed_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_airspeed_plugin.cpp.s
.PHONY : src/sensor_airspeed_plugin.cpp.s

src/sensor_baro_plugin.o: src/sensor_baro_plugin.cpp.o

.PHONY : src/sensor_baro_plugin.o

# target to build an object file
src/sensor_baro_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_baro_plugin.cpp.o
.PHONY : src/sensor_baro_plugin.cpp.o

src/sensor_baro_plugin.i: src/sensor_baro_plugin.cpp.i

.PHONY : src/sensor_baro_plugin.i

# target to preprocess a source file
src/sensor_baro_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_baro_plugin.cpp.i
.PHONY : src/sensor_baro_plugin.cpp.i

src/sensor_baro_plugin.s: src/sensor_baro_plugin.cpp.s

.PHONY : src/sensor_baro_plugin.s

# target to generate assembly for a file
src/sensor_baro_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_baro_plugin.cpp.s
.PHONY : src/sensor_baro_plugin.cpp.s

src/sensor_gps_plugin.o: src/sensor_gps_plugin.cpp.o

.PHONY : src/sensor_gps_plugin.o

# target to build an object file
src/sensor_gps_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_gps_plugin.cpp.o
.PHONY : src/sensor_gps_plugin.cpp.o

src/sensor_gps_plugin.i: src/sensor_gps_plugin.cpp.i

.PHONY : src/sensor_gps_plugin.i

# target to preprocess a source file
src/sensor_gps_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_gps_plugin.cpp.i
.PHONY : src/sensor_gps_plugin.cpp.i

src/sensor_gps_plugin.s: src/sensor_gps_plugin.cpp.s

.PHONY : src/sensor_gps_plugin.s

# target to generate assembly for a file
src/sensor_gps_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_gps_plugin.cpp.s
.PHONY : src/sensor_gps_plugin.cpp.s

src/sensor_imu_plugin.o: src/sensor_imu_plugin.cpp.o

.PHONY : src/sensor_imu_plugin.o

# target to build an object file
src/sensor_imu_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_imu_plugin.cpp.o
.PHONY : src/sensor_imu_plugin.cpp.o

src/sensor_imu_plugin.i: src/sensor_imu_plugin.cpp.i

.PHONY : src/sensor_imu_plugin.i

# target to preprocess a source file
src/sensor_imu_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_imu_plugin.cpp.i
.PHONY : src/sensor_imu_plugin.cpp.i

src/sensor_imu_plugin.s: src/sensor_imu_plugin.cpp.s

.PHONY : src/sensor_imu_plugin.s

# target to generate assembly for a file
src/sensor_imu_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_imu_plugin.cpp.s
.PHONY : src/sensor_imu_plugin.cpp.s

src/sensor_mag_plugin.o: src/sensor_mag_plugin.cpp.o

.PHONY : src/sensor_mag_plugin.o

# target to build an object file
src/sensor_mag_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_mag_plugin.cpp.o
.PHONY : src/sensor_mag_plugin.cpp.o

src/sensor_mag_plugin.i: src/sensor_mag_plugin.cpp.i

.PHONY : src/sensor_mag_plugin.i

# target to preprocess a source file
src/sensor_mag_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_mag_plugin.cpp.i
.PHONY : src/sensor_mag_plugin.cpp.i

src/sensor_mag_plugin.s: src/sensor_mag_plugin.cpp.s

.PHONY : src/sensor_mag_plugin.s

# target to generate assembly for a file
src/sensor_mag_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_mag_plugin.cpp.s
.PHONY : src/sensor_mag_plugin.cpp.s

src/sensor_plugin.o: src/sensor_plugin.cpp.o

.PHONY : src/sensor_plugin.o

# target to build an object file
src/sensor_plugin.cpp.o:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_plugin.cpp.o
.PHONY : src/sensor_plugin.cpp.o

src/sensor_plugin.i: src/sensor_plugin.cpp.i

.PHONY : src/sensor_plugin.i

# target to preprocess a source file
src/sensor_plugin.cpp.i:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_plugin.cpp.i
.PHONY : src/sensor_plugin.cpp.i

src/sensor_plugin.s: src/sensor_plugin.cpp.s

.PHONY : src/sensor_plugin.s

# target to generate assembly for a file
src/sensor_plugin.cpp.s:
	$(MAKE) -f CMakeFiles/jsbsim_bridge.dir/build.make CMakeFiles/jsbsim_bridge.dir/src/sensor_plugin.cpp.s
.PHONY : src/sensor_plugin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... jsbsim_bridge"
	@echo "... src/actuator_plugin.o"
	@echo "... src/actuator_plugin.i"
	@echo "... src/actuator_plugin.s"
	@echo "... src/configuration_parser.o"
	@echo "... src/configuration_parser.i"
	@echo "... src/configuration_parser.s"
	@echo "... src/geo_mag_declination.o"
	@echo "... src/geo_mag_declination.i"
	@echo "... src/geo_mag_declination.s"
	@echo "... src/jsbsim_bridge.o"
	@echo "... src/jsbsim_bridge.i"
	@echo "... src/jsbsim_bridge.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mavlink_interface.o"
	@echo "... src/mavlink_interface.i"
	@echo "... src/mavlink_interface.s"
	@echo "... src/sensor_airspeed_plugin.o"
	@echo "... src/sensor_airspeed_plugin.i"
	@echo "... src/sensor_airspeed_plugin.s"
	@echo "... src/sensor_baro_plugin.o"
	@echo "... src/sensor_baro_plugin.i"
	@echo "... src/sensor_baro_plugin.s"
	@echo "... src/sensor_gps_plugin.o"
	@echo "... src/sensor_gps_plugin.i"
	@echo "... src/sensor_gps_plugin.s"
	@echo "... src/sensor_imu_plugin.o"
	@echo "... src/sensor_imu_plugin.i"
	@echo "... src/sensor_imu_plugin.s"
	@echo "... src/sensor_mag_plugin.o"
	@echo "... src/sensor_mag_plugin.i"
	@echo "... src/sensor_mag_plugin.s"
	@echo "... src/sensor_plugin.o"
	@echo "... src/sensor_plugin.i"
	@echo "... src/sensor_plugin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

